apiVersion: v1
kind: Service
metadata:
  name: user2-service
  namespace: user2
spec:
  selector:
    app: user2-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

